version: "3.9"
services:
  postgres:
    image: "postgres:14.2"
    container_name: "psql"
    restart: always
    environment:
      POSTGRES_DB: ${DB_BACKEND}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: ${PG_DATA}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - database-network

  app:
    build:
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - database-network
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - postgres

networks:
  database-network: # Name in this docker-compose file
    driver: bridge