version: "3.9"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
    - database-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
#        like mongodb://root:example@mongo:27017/

#  app:
#    build:
#      dockerfile: Dockerfile
#    env_file:
#      - ./.env
#    networks:
#      - database-network
#    restart: on-failure
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

networks:
  database-network: # Name in this docker-compose file
    driver: bridge

